### ISSUE TITLE
Recurrence occurs for each post

### ISSUE THREAD

**Issue by fisal77** [SALLEMAPP/sallem-app#3]
After enter new post the app redirect the user to the user's Post(s) view activity but after few minutes, a recurrence occurs for each post.

**Comment by bamusasoft** [comment]
Fixed. This is a bug introduced due to change in how local caching works.

**Comment by fisal77** [comment]
Dear Mr. @bamusasoft 

The issue still back again !

Please help us.

**Comment by SALLEMAPP** [comment]
Would you please pull the latest commit and check.

**Comment by fisal77** [comment]
Yes ! Thank you >>>> The issue solved !
